- name: Copy temporary busybox
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/busybox"
    output_file_path: "/tmp/busybox"
    output_file_owner: "root"
    output_file_group: "root"
    output_file_chmod: "755"

- name: Copy Agent File
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/cmp-agent.tar.xz"
    output_file_path: "/tmp/cmp-agent.tar.xz"
    output_file_owner: "root"
    output_file_group: "root"
    output_file_chmod: "644"

- name: Copy Agent binary
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  shell: "/tmp/busybox tar xvf /tmp/cmp-agent.tar.xz -C /usr/bin/"

- name: Copy iptables static
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/iptables-static.tar.xz"
    output_file_path: "/tmp/iptables-static.tar.xz"
    output_file_owner: "root"
    output_file_group: "root"
    output_file_chmod: "644"

- name: Copy iptables static binaries
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  shell: "/tmp/busybox tar xvf /tmp/iptables-static.tar.xz -C /"

- name: Add iptables static binaries to PATH environment
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  shell: "sed -i '/export PATH=/iptables-static/sbin:$PATH/d' /etc/profile && echo 'export PATH=/iptables-static/sbin:$PATH' >> /etc/profile && export PATH=/iptables-static/sbin:$PATH"

- name: Remove temporary busybox
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  shell: "rm -f /tmp/busybox"

- name: Create Agent config folder
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  raw: "mkdir -p /etc/cmp-agent/"

- name: Copy Agent config file
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/config/config"
    output_file_path: "/etc/cmp-agent/config"
    output_file_owner: "root"
    output_file_group: "root"
    output_file_chmod: "644"

- name: Copy Agent service file
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/systemd/cmp-agent.service"
    output_file_path: "/lib/systemd/system/cmp-agent.service"
    output_file_owner: "root"
    output_file_group: "root"
    output_file_chmod: "644"

- name: Reload systemctl daemon
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  raw: "systemctl daemon-reload"

- name: Enable Agent service
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  raw: "systemctl enable cmp-agent"

- name: Restart Agent service
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  shell: "systemctl restart cmp-agent"

- name: Run Agent status command
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  raw: "systemctl status --no-pager cmp-agent"
  register: agent_status
  failed_when: agent_status.rc not in [0, 3]

- name: Display Agent status
  debug:
    var: agent_status
