- name: Copy Agent binary
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/bin/cmp-agent"
    output_file_path: "/usr/bin/cmp-agent"
    output_file_chown: "root:root"
    output_file_chmod: "755"

- name: Copy Agent service file
  include_tasks: send_file.yaml
  vars:
    input_file_path: "{{ role_path }}/agent-install-files/systemd/cmp-agent.service"
    output_file_path: "/lib/systemd/system/cmp-agent.service"
    output_file_chown: "root:root"
    output_file_chmod: "644"

- name: Reload systemctl daemon
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: localhost
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  raw: "systemctl daemon-reload"

- name: Restart Agent service
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: localhost
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  raw: "systemctl restart cmp-agent"
