- name: Check required variables
  fail: 
    msg: "Required variable not found: {{ item }}"
  when: vars[item] is not defined or vars[item] == ''
  loop:
    - target_host
    - target_port
    - target_user
    - target_password
