services:
  semaphore:
    build:
      context: .
      dockerfile: Dockerfile.semaphore
    container_name: semaphore
    restart: always
    ports:
      - 3000:3000
    environment:
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB_HOST: semaphore-db
      SEMAPHORE_DB_NAME: semaphore
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphorepass
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: semaphorepass
      SEMAPHORE_ADMIN_NAME: ish
      SEMAPHORE_ADMIN_EMAIL: ish@innogrid.com
      ANSIBLE_HOST_KEY_CHECKING: False
    volumes:
      - ./container-volume/ansible:/ansible
      - ./data/semaphore:/var/lib/semaphore
    networks:
      - ansible-network
    depends_on:
      - semaphore-db

  semaphore-db:
    image: mariadb:11.6
    container_name: semaphore-db
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_USER: semaphore
      MARIADB_PASSWORD: semaphorepass
      MARIADB_DATABASE: semaphore
      MARIADB_ROOT_PASSWORD: semaphorepass
    volumes:
      - ./container-volume/mariadb/tunnel-manager.sql:/docker-entrypoint-initdb.d/tunnel-manager.sql
      - ./data/mariadb:/var/lib/mysql
    networks:
      - ansible-network

  test-influxdb:
    image: influxdb:1.8
    container_name: test-influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_USER=cmp-agent
      - INFLUXDB_PASSWORD=cmp-agent
      - INFLUXDB_DB="cmp"
    volumes:
      - ./data/influxdb/config:/etc/influxdb
      - ./data/influxdb/var/lib/influxdb:/root/.influxdb
    networks:
      - influxdb-network

  test-chronograf:
    image: chronograf:1.9.4
    container_name: test-chronograf
    restart: always
    ports:
      - 8888:8888
    environment:
      - INFLUXDB_URL=http://test-influxdb:8086
      - INFLUXDB_USERNAME=cmp-agent
      - INFLUXDB_PASSWORD=cmp-agent
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    networks:
      - influxdb-network
    depends_on:
      - test-influxdb

networks:
  ansible-network:
    name: ansible-network
  influxdb-network:
    name: influxdb-network
