FROM semaphoreui/semaphore:v2.11.2

USER root

RUN apk --no-cache add tzdata
RUN echo "Asia/Seoul" >  /etc/timezone
RUN cp -f /usr/share/zoneinfo/Asia/Seoul /etc/localtime

RUN apk add sudo
RUN apk add openssh
RUN apk add iproute2

RUN echo "semaphore ALL = NOPASSWD: ALL" >> /etc/sudoers

USER semaphore
