- hosts: 127.0.0.1
  gather_facts: no
  vars:
    ansible_python_interpreter: python3
  tasks:
    - name: Check variables
      include_role:
        name: check

    - name: Install tunnel-manager
      include_role:
        name: tunnel-manager
