- name: Copy file to remote
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: 127.0.0.1
    ansible_port: "{{ tunnel_port }}"
    ansible_user: "{{ target_user }}"
    ansible_password: "{{ target_password }}"
    ansible_become_password: "{{ target_password }}"
  copy:
    src: "{{ input_file_path }}"
    dest: "{{ output_file_path }}"
    mode: "{{ output_file_chmod }}"
    owner: "{{ output_file_owner }}"
    group: "{{ output_file_group }}"
